<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260102223244 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account_bank (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, bank_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_bank_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54F338D049C5E54B ON account_bank (user_bank_id)');
        $this->addSql('CREATE TABLE booklet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, max_amount INT DEFAULT NULL, bank_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_818DB72011C8FB41 ON booklet (bank_id)');
        $this->addSql('CREATE TABLE recurring_transaction (recurrence_type VARCHAR(255) NOT NULL, day INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note VARCHAR(255) NOT NULL, amount INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booklet_id INT NOT NULL, label_id INT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1668144B3 ON transaction (booklet_id)');
        $this->addSql('CREATE INDEX IDX_723705D133B92F39 ON transaction (label_id)');
        $this->addSql('CREATE TABLE transaction_label (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color_bg VARCHAR(7) DEFAULT NULL, color_txt VARCHAR(7) DEFAULT NULL, user_label_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF9480A8D334CB39 ON transaction_label (user_label_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE TABLE user_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, profile_img VARCHAR(255) DEFAULT NULL, color_accent VARCHAR(7) DEFAULT NULL, lang VARCHAR(5) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, attached_user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C779A692E28AEC91 ON user_setting (attached_user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE account_bank ADD CONSTRAINT FK_54F338D049C5E54B FOREIGN KEY (user_bank_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booklet ADD CONSTRAINT FK_818DB72011C8FB41 FOREIGN KEY (bank_id) REFERENCES account_bank (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recurring_transaction ADD CONSTRAINT FK_D3509AA6BF396750 FOREIGN KEY (id) REFERENCES transaction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1668144B3 FOREIGN KEY (booklet_id) REFERENCES booklet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D133B92F39 FOREIGN KEY (label_id) REFERENCES transaction_label (id)');
        $this->addSql('ALTER TABLE transaction_label ADD CONSTRAINT FK_AF9480A8D334CB39 FOREIGN KEY (user_label_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A692E28AEC91 FOREIGN KEY (attached_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account_bank DROP CONSTRAINT FK_54F338D049C5E54B');
        $this->addSql('ALTER TABLE booklet DROP CONSTRAINT FK_818DB72011C8FB41');
        $this->addSql('ALTER TABLE recurring_transaction DROP CONSTRAINT FK_D3509AA6BF396750');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1668144B3');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D133B92F39');
        $this->addSql('ALTER TABLE transaction_label DROP CONSTRAINT FK_AF9480A8D334CB39');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A692E28AEC91');
        $this->addSql('DROP TABLE account_bank');
        $this->addSql('DROP TABLE booklet');
        $this->addSql('DROP TABLE recurring_transaction');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE transaction_label');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_setting');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
